export const actionTypes = {
  NEW_GAME: 'NEW_GAME',
  ADD_SCORE: 'ADD_SCORE',
  SHOW_ALERT: 'SHOW_ALERT',
  SET_ANSWER: 'SET_ANSWER',
  USER_LOGIN: 'USER_LOGIN',
  HIDE_ALERT: 'HIDE_ALERT',
  NEXT_QUESTION: 'NEXT_QUESTION',
  CORRECT_ANSWER: 'CORRECT_ANSWER',
  FETCH_QUESTIONS: 'FETCH_QUESTIONS',
  SELECT_QUESTION: 'SELECT_QUESTION',
  PREVIOUS_QUESTION: 'PREVIOUS_QUESTION',
  UPDATE_TOTAL_ANSWERS: 'UPDATE_TOTAL_ANSWERS',
}
